# Generated by Django 5.2.12 on 2026-03-30 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryOption",
            fields=[
                (
                    "id",
                    models.SlugField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("fee", models.PositiveIntegerField(default=0)),
                ("eta_days", models.PositiveSmallIntegerField(default=7)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=128, null=True)),
                ("status", models.CharField(default="pending", max_length=32)),
                (
                    "payment_status",
                    models.CharField(default="not_uploaded", max_length=32),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("delivery_option_id", models.CharField(blank=True, max_length=64)),
                ("delivery_label", models.CharField(blank=True, max_length=200)),
                ("delivery_description", models.TextField(blank=True)),
                ("delivery_eta_days", models.PositiveSmallIntegerField(default=7)),
                ("tracking_number", models.CharField(blank=True, max_length=200)),
                ("carrier", models.CharField(blank=True, max_length=200)),
                ("items", models.JSONField(default=list)),
                ("customer_info", models.JSONField(default=dict)),
                ("payment_screenshot", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
