# Generated by Django 5.2.12 on 2026-04-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_proof_images',
            field=models.JSONField(blank=True, default=list, help_text='Relative media paths for partner proof-of-delivery photos.'),
        ),
    ]
