# Generated by Django 5.2.12 on 2026-04-09 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=64)),
                ('license_image', models.ImageField(upload_to='delivery_partners/licenses/%Y/%m/')),
                ('aadhar_number', models.CharField(max_length=20)),
                ('aadhar_image', models.ImageField(upload_to='delivery_partners/aadhar/%Y/%m/')),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_image', models.ImageField(upload_to='delivery_partners/pan/%Y/%m/')),
                ('city', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('password_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_partner_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='delivery_pa_created_57cfdb_idx')],
            },
        ),
    ]
